### ISSUE TITLE
Links not readable

### ISSUE THREAD

**Issue by muescha** [timo-reymann/learnings#1]
### What happened?

link is unreadable (white on white)

![Bildschirmfoto 2023-08-16 um 18 06 27](https://github.com/timo-reymann/learnings/assets/184316/97aa446c-002f-4032-ac21-36b20e208ce2)

### Problem description

this makes the link unreadable (white on white)

```css
.index-link {
    color: #fcfaf9;
}
```
https://github.com/timo-reymann/learnings/blob/1981ab80b1d9c5254c3dd27c939c4bc15b026193/assets/css/style.scss#L29-L31

### Expected behaviour

dark link color

### Actual  behaviour

light grey link color

### Steps to Reproduce

open https://learnings.timo-reymann.de/

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
Thanks for reporting, should be fixed with the changes from 1f520256a512bf96f6fcff064a676772c5276cd4
